apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-watcher
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-watcher
  template:
    metadata:
      labels:
        app: velero-watcher
    spec:
      serviceAccountName: velero-watcher-sa
      containers:
      - name: velero-watcher
        image: kadirkaraharman/velero-notification-k8s:1.0.1
        resources:
            requests:
                memory: "200Mi"
                cpu: "100m"
            limits:
                memory: "300Mi"
                cpu: "200m"
        envFrom:
        - configMapRef:
            name: velero-watcher-config
        ports:
        - containerPort: 8081
        securityContext:
          readOnlyRootFilesystem: true 
          runAsNonRoot: true            
          runAsUser: 1000               
---
apiVersion: v1
kind: Service
metadata:
  name: velero-watcher-service
  namespace: velero
spec:
  selector:
    app: velero-watcher
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8081  
  type: NodePort       


