apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: velero
  name: velero-backup-reader
rules:
- apiGroups: ["velero.io"]
  resources: ["backups"]
  verbs: ["get", "list", "watch"]