apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-backup-reader-binding
  namespace: velero
subjects:
- kind: ServiceAccount
  name: velero-watcher-sa
  namespace: velero
roleRef:
  kind: Role
  name: velero-backup-reader
  apiGroup: rbac.authorization.k8s.io